apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: k3os-config-operator
build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/annismckenzie/k3os-config-operator
      custom:
        buildCommand: make docker-build
profiles:
  - name: release
    build:
      tagPolicy:
        gitCommit: {}
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - config/default
  - name: dev
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevTreeSha
          prefix: dev-
      local:
        push: true
