apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: k3os-config-operator
build:
  local:
    push: false
profiles:
  - name: release
    build:
      artifacts:
        - image: ghcr.io/annismckenzie/k3os-config-operator
          custom:
            buildCommand: make docker-build
      tagPolicy:
        gitCommit: {}
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - config/default
  - name: dev
    build:
      artifacts:
        - image: ghcr.io/annismckenzie/k3os-config-operator
          custom:
            buildCommand: make docker-build-dev
      tagPolicy:
        gitCommit:
          variant: AbbrevTreeSha
          prefix: dev-
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - config/dev
