# permissions for end users to view k3osconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3osconfig-viewer-role
rules:
- apiGroups:
  - config.operators.annismckenzie.github.com
  resources:
  - k3osconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operators.annismckenzie.github.com
  resources:
  - k3osconfigs/status
  verbs:
  - get
