# permissions for end users to view k3osconfigfiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3osconfigfile-viewer-role
rules:
- apiGroups:
  - config.operators.annismckenzie.github.com
  resources:
  - k3osconfigfiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operators.annismckenzie.github.com
  resources:
  - k3osconfigfiles/status
  verbs:
  - get
